name: Build and publish release

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew build

      - name: Checkout monument
        uses: actions/checkout@v2
        with:
          ref: monument

      - name: Build with Gradle
        run: ./gradlew build

      - name: Checkout classic
        uses: actions/checkout@v2
        with:
          ref: classic

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        if: ${{ always() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          release_name: ${{ steps.vars.outputs.tag }}
          body: |
            <CHANGELOG>

            Make sure to read the [README](README.md) for instructions on how the mod works and how to use it.
          draft: true
          prerelease: false

      - name: Upload all artifacts
        uses: xresloader/upload-to-github-release@v1
        if: ${{ always() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: 'build/libs/noverworld-*.jar'
          delete_file: 'build/libs/noverworld-*dev.jar;build/libs/noverworld-*sources.jar'
          release_id: ${{ steps.create_release.outputs.id }}
          overwrite: true
          verbose: true
